"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2025-11-28 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_features',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_resource_id', sa.String(length=255), nullable=False),
        sa.Column('gender', sa.String(length=50), nullable=True),
        sa.Column('birth_date', sa.String(length=50), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('num_encounters', sa.Integer(), nullable=True, default=0),
        sa.Column('avg_los', sa.Float(), nullable=True, default=0.0),
        sa.Column('num_conditions', sa.Integer(), nullable=True, default=0),
        sa.Column('num_med_requests', sa.Integer(), nullable=True, default=0),
        sa.Column('obs_abnormal_count', sa.Integer(), nullable=True, default=0),
        sa.Column('ner_entities', sa.JSON(), nullable=True),
        sa.Column('embedding_mean', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_features_id'), 'patient_features', ['id'], unique=False)
    op.create_index(op.f('ix_patient_features_patient_resource_id'), 'patient_features', ['patient_resource_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_features_patient_resource_id'), table_name='patient_features')
    op.drop_index(op.f('ix_patient_features_id'), table_name='patient_features')
    op.drop_table('patient_features')
    # ### end Alembic commands ###